### ISSUE TITLE
add aest as a timezone

### ISSUE THREAD

**Issue by Jksleey** [zwang20/deployment-bot-6#8]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when i cant see the time of my country

**Describe the solution you'd like**
bot returns aest time

**Describe alternatives you've considered**
datetime function idk lol

**Additional context**

**Comment by zwang20** [comment]
`time Etc/GMT-10` 
should be used for AEST and 
`time Australia/Sydney`
should be used for local time at Sydney, Australia.
